[package]
name = "twilio"
version = "0.1.3"
description = "Rust bindings for the Twilio API"
readme = "README.md"
repository = "https://github.com/neil-lobracco/twilio-rs"
license = "MIT"
authors = ["Neil LoBracco <neil.lobracco@gmail.com>", "Lance Carlson <lancecarlson@gmail.com>"]
keywords = ["twilio","rust"]
edition = "2018"

[dependencies]
base64 = "0.12"
headers = "0.3.2"
hyper = "0.13"
hyper-tls = "0.4"
mime = "0.3"
serde = "1.0.10"
serde_derive = "1.0.10"
serde_json = "1.0.2"
rust-crypto = "0.2"
url = "2.0"

[dev-dependencies]
dotenv = "0.15"
tokio = { version = "0.2", features = ["macros", "rt-core", "test-util"] }
